import { absoluteTime } from '../../lib/format';
import type { Rca as RcaType } from '../../lib/types';

/**
 * Root cause analysis: the only generated prose on the page.
 *
 * It is boxed, tinted and labelled so it can never be mistaken for the measured
 * facts above it. The rules decide whether something is wrong; this only
 * explains why, and the two must not blur.
 *
 * `model: "template"` means the deterministic fallback wrote it and no model
 * ran. Presenting that as model output would be a lie in one direction, and
 * presenting model output as measured fact a lie in the other.
 */
export function Rca({ rca }: { rca: RcaType | null }): React.JSX.Element {
  if (!rca) {
    return (
      <section className="panel section">
        <header className="section__head">
          <h2 className="eyebrow eyebrow--accent">Root cause analysis</h2>
        </header>
        {/* Not an error: diagnosis runs after detection, and an incident can be
            correct and complete without it. */}
        <p className="soft section__empty">
          Not generated yet. Detection does not wait for it, so an incident is complete without one.
        </p>
      </section>
    );
  }

  const template = rca.model === 'template';

  return (
    <section className="panel section rca">
      <header className="section__head">
        <h2 className="eyebrow eyebrow--accent">Root cause analysis</h2>
        <div className="rca__origin">
          <span className={template ? 'rca__badge rca__badge--template' : 'rca__badge'}>
            {template ? 'deterministic template — no model ran' : `generated by ${rca.model}`}
          </span>
          <span className="section__gap" />
          <span className="dim mono">{absoluteTime(rca.generatedAt)}</span>
        </div>
      </header>

      <p className="rca__summary">{rca.summary}</p>

      {rca.contributingFactors.length > 0 ? (
        <div className="subsection">
          <h3 className="eyebrow">Contributing factors</h3>
          <ul className="rca__list">
            {rca.contributingFactors.map((factor) => (
              <li key={factor}>{factor}</li>
            ))}
          </ul>
        </div>
      ) : null}

      {rca.timeline && rca.timeline.length > 0 ? (
        <div className="subsection">
          <h3 className="eyebrow">Reconstructed sequence</h3>
          <ul className="rca__list rca__list--timeline">
            {rca.timeline.map((entry) => (
              <li key={`${entry.at}-${entry.what}`}>
                <span className="mono dim">{absoluteTime(entry.at)}</span> {entry.what}
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      <div className="subsection">
        <h3 className="eyebrow">Recommendation</h3>
        <p className="rca__recommendation">{rca.recommendation}</p>
      </div>

      {rca.promptVersion ? (
        <p className="dim mono rca__version">prompt {rca.promptVersion}</p>
      ) : null}
    </section>
  );
}
